# Oh-my-zsh theme
ZSH_THEME="minimal"

# Path to your oh-my-zsh installation.
export ZSH=/home/alathon/.oh-my-zsh
source $ZSH/oh-my-zsh.sh

# Java
export JDK_HOME=/usr/lib/jvm/java-8-openjdk

#source $HOME/.config/zsh/zsh-nix-shell/nix-shell.plugin.zsh

# Plugins to load
plugins=(git github nix-shell)

# Nix-shell stuff
#source $HOME/.config/zsh/nix-zsh-completions/nix.plugin.zsh
#  fpath=$($HOME/.config/zsh/nix-zsh-completions $fpath)

# User configuration
export SCALA_HOME="/usr/local/share/scala-2.11.8/"
export ANDROID_HOME="/home/alathon/Android/Sdk/"

# Preferred editor for local and remote sessions
export NVIM_LISTEN_ADDRESS=/tmp/nvimsocket
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='nvim'
else
  export EDITOR='nvim'
fi

# Compilation flags
export ARCHFLAGS="-arch x86_64"

# ssh
export SSH_KEY_PATH="~/.ssh/id_rsa"
# SSH Keychain
eval $(keychain --eval --quiet --noask id_rsa)

# FZF
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_COMMAND='ag -g ""'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

# fzf-scanned bookmark method. Searches through .cdg_paths and /etc/cdg_paths
unalias cdg 2> /dev/null
cdg() {
  local dest_dir=$(cdscuts_glob_echo | fzf)
  if [[ $dest_dir != '' ]]; then
    cd "$dest_dir"
  fi
}

fe() {
  IFS='
'
  local declare files=($(fzf-tmux --query="$1" --select-1 --exit-0))
  [[ -n "$files" ]] && ${EDITOR:-nvim} "${files[@]}"
  unset IFS
}

# Path
export PATH=/home/alathon/.dotnet/tools:/home/alathon/.jx/bin:/home/alathon/.local/bin:/home/alathon/.fzf/bin:/home/alathon/.npm-global/bin:$PATH

# Dircolors
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
eval $( dircolors -b $HOME/.dircolors )


# Syntax highlighting based on LS_COLORS
source $HOME/.config/zsh/zsh-syntax-highlighting-filetypes.zsh

# AutoEnv
source ~/.dotfiles/lib/zsh-autoenv/autoenv.zsh

# Paket alias for F#
alias paket='mono ./.paket/paket.exe'
unsetopt completealiases
compdef _precommand mono
zstyle ':completion::complete:paket:*' use-fallback no # Disable default zsh completion for Paket

alias git=hub
alias tmux="tmux -2 $argv"
alias scaut='tmux new-session -A -s scaut'
alias vim="nvim"
alias oldvim="vim"
alias clean-docker="sh ~/.local/bin/clean-docker.sh"

# Dotnet root
export DOTNET_ROOT=/opt/dotnet
export MSBuildSDKsPath=/opt/dotnet/sdk/2.1.403/Sdks

autoload -Uz compinit && compinit
